export {
  SET_LIKE_STRING_ARRAY_FIELDS,
  canonicalizeJson,
  compareCodeUnits,
  normalizeComments,
  normalizeSetArrays,
  sha256Jcs,
  sha256NormalizedJcs,
  sortAndDedupeStrings,
  type NormalizableComment,
} from "./canonical.js";
export {
  DEFAULT_CONFIG_FILE_NAME,
  RepoKnowledgeConfigError,
  computeOutputSchemaDigest,
  computePromptDigest,
  computeTrustPolicyDigest,
  initializeStorage,
  loadRepoKnowledgeConfig,
  parseRepoKnowledgeConfig,
  resolveRepositoryPolicy,
  type ConfigErrorCode,
  type EffectiveRepositoryPolicy,
  type InitializedStorage,
} from "./config.js";
export {
  ActorKindSchema,
  AiProviderSchema,
  CandidateIdSchema,
  CommentObservationSchema,
  DistillJobSchema,
  DistillJobStateSchema,
  DistillationOutputSchema,
  DistilledCandidateSchema,
  EventIdSchema,
  EvidenceActorSchema,
  EvidenceIdSchema,
  EvidenceStatusSchema,
  ExtractCandidateSchema,
  ExtractStableResponseSchema,
  ExtractSubmissionReceiptSchema,
  FinalizeStableResponseSchema,
  FinalizeSubmissionReceiptSchema,
  GitHubNodeIdSchema,
  HostAssistedDistillationConfigSchema,
  IngestConfigSchema,
  IsoDateTimeSchema,
  JobIdSchema,
  KnowledgeCategorySchema,
  KnowledgeEvidenceSchema,
  KnowledgeIdSchema,
  KnowledgeStatusSchema,
  LlmConfigSchema,
  MergeDecisionRequiredStableResponseSchema,
  MergeDecisionSchema,
  MergeRelationSchema,
  NonEmptyStringSchema,
  ObservationIdSchema,
  PullRequestObservationSchema,
  PullRequestSnapshotSchema,
  RawObservationSchema,
  ReceiptIdSchema,
  RepoKnowledgeConfigSchema,
  RepositoryIdSchema,
  RepositoryNameSchema,
  RepositoryPolicySchema,
  ReviewerIdentitySchema,
  ScopePatternSchema,
  SeveritySchema,
  Sha256DigestSchema,
  SkipReasonSchema,
  SkippedStableResponseSchema,
  SnapshotIdSchema,
  SourceProviderSchema,
  SubmissionReceiptSchema,
  ThreadObservationSchema,
  TransactionIdSchema,
  TrustConfigSchema,
  TrustLevelSchema,
  type CommentObservation,
  type DistillJob,
  type DistillationOutput,
  type DistilledCandidate,
  type EvidenceActor,
  type EvidenceStatus as DomainEvidenceStatus,
  type ExtractCandidate as DomainExtractCandidate,
  type ExtractStableResponse as DomainExtractStableResponse,
  type FinalizeStableResponse,
  type HostAssistedDistillationConfig,
  type IngestConfig,
  type KnowledgeCategory,
  type KnowledgeEvidence,
  type KnowledgeStatus,
  type LlmConfig,
  type MergeDecision,
  type MergeDecisionRequiredStableResponse as DomainMergeDecisionRequiredStableResponse,
  type PullRequestObservation,
  type PullRequestSnapshot,
  type RawObservation,
  type RepoKnowledgeConfig,
  type RepositoryPolicy,
  type ReviewerIdentity,
  type Severity,
  type SubmissionReceipt,
  type ThreadObservation,
  type TrustConfig,
} from "./domain-schemas.js";
export {
  DOMAIN_ID_PREFIXES,
  createDomainId,
  type DomainIdKind,
} from "./ids.js";
export {
  CanonicalJsonlError,
  canonicalJsonlLineSha256,
  parseCanonicalJsonlLine,
  serializeCanonicalJsonlRecord,
  type CanonicalJsonlRecord,
} from "./canonical-jsonl.js";
export {
  CanonicalStoreError,
  CanonicalTransactionStore,
  KnowledgeConflictError,
  type CanonicalAppendRecordRequest,
  type CanonicalCommitPoint,
  type CanonicalFaultContext,
  type CanonicalFaultInjector,
  type CanonicalFileWriteRequest,
  type CanonicalStoreErrorCode,
  type CanonicalTransactionRequest,
  type CanonicalTransactionStoreOptions,
  type KnowledgeUpdateRequest,
} from "./canonical-transaction-store.js";
export {
  DEFINITIVE_NON_KNOWLEDGE_SKIP_REASONS,
  applySkipReasonPolicy,
  isDefinitiveNonKnowledge,
  type DefinitiveNonKnowledgeSkipReason,
  type EvidenceRecord,
  type EvidenceStatus,
  type ManualReviewMarker,
  type SkipPolicyInput,
  type SkipPolicyResult,
  type SkipReason,
  type SkippedStableResponse,
} from "./evidence-policy.js";
export {
  FinalizeGuard,
  FinalizeGuardError,
  computeContentFingerprint,
  computeDistillationKey,
  computeMatchSetDigest,
  normalizePossibleMatchBindings,
  type CurrentFinalizeSource,
  type DistillationKeyInput,
  type FinalizeContext,
  type FinalizeGuardDependencies,
  type FinalizeGuardErrorCode,
  type FinalizeJob,
  type FingerprintComment,
} from "./finalize-guard.js";
export {
  ProjectionStaleError,
  buildKnowledgeProjection,
  computeKnowledgeFileState,
  ensureProjectionCurrent,
  isProjectionCurrent,
  readKnowledgeSnapshot,
  type KnowledgeFile,
  type KnowledgeFileHash,
  type KnowledgeFileState,
  type KnowledgeProjection,
  type KnowledgeProjectionBuilder,
  type KnowledgeSnapshot,
} from "./knowledge-file-state.js";
export {
  KnowledgeStoreInvalidError,
  applyKnowledgeDocumentPatch,
  computeByteSha256,
  parseKnowledgeDocument,
  serializeKnowledgeDocument,
  type KnowledgeDocument,
  type KnowledgeDocumentPatch,
  type KnowledgeFrontmatter,
} from "./knowledge-document.js";
export { FileLockTimeoutError, withPosixFileLock } from "./posix-file-lock.js";
export {
  RequestIntegrityError,
  SubmissionIdempotencyStore,
  buildRequestHashPayload,
  computeRequestSha256,
  issueRequestBoundToken,
  verifyRequestBoundToken,
  type AcceptedSubmissionRegistration,
  type ExpectedRequestBoundToken,
  type ExtractRequest,
  type ExtractRequestHashPayload,
  type FinalizeRequest,
  type FinalizeRequestHashPayload,
  type IssueRequestBoundTokenInput,
  type PhaseRequest,
  type ReplaySubmissionRegistration,
  type RequestBoundTokenClaims,
  type RequestBoundTokenKind,
  type RequestHashPayload,
  type RequestIntegrityErrorCode,
  type SubmissionRegistration,
} from "./request-integrity.js";
export {
  InMemoryReceiptStore,
  ReceiptReplayEngine,
  ReceiptReplayError,
  type ExtractCandidate,
  type ExtractReceipt,
  type ExtractReplayResult,
  type ExtractRuntimeResponse,
  type ExtractStableResponse,
  type FinalizeReceipt,
  type FinalizeReplayResult,
  type MergeDecisionRequiredRuntimeResponse,
  type MergeDecisionRequiredStableResponse,
  type PossibleMatchBinding,
  type Receipt,
  type ReceiptMissResult,
  type ReceiptReplayDependencies,
  type ReceiptReplayErrorCode,
  type ReceiptReplayResult,
  type ReceiptStore,
  type ReplayJob,
} from "./receipt-replay.js";
export {
  RepositoryRegistry,
  RepositoryRegistryError,
  repositoryStorageId,
  type RegisterRepositoryRequest,
  type RepositoryRegistryEntry,
  type RepositoryRegistryErrorCode,
  type RepositoryRegistryOptions,
  type ResolvedRepository,
} from "./repository-registry.js";
export {
  SqliteCanonicalProjection,
  type CanonicalProjectionSnapshot,
  type ProjectedCanonicalRecord,
} from "./sqlite-projection.js";
