export {
  DEFAULT_ADMIN_POSSIBLE_MATCH_LIMIT,
  AdminPlaneError,
  AdminPlaneService,
  type AdminAddActiveInput,
  type AdminEvidenceReview,
  type AdminInteractionResult,
  type AdminKnowledgeReview,
  type AdminKnowledgeSummary,
  type AdminPlaneErrorCode,
  type AdminPlaneServiceOptions,
  type AdminPossibleMatch,
  type AdminReviewQueue,
  type AdminRevisionProposalReview,
  type AdminRevisionProposalSummary,
} from "./admin-plane-service.js";
export {
  SET_LIKE_STRING_ARRAY_FIELDS,
  canonicalizeJson,
  compareCodeUnits,
  normalizeComments,
  normalizeSetArrays,
  sha256Jcs,
  sha256NormalizedJcs,
  sortAndDedupeStrings,
  type NormalizableComment,
} from "./canonical.js";
export {
  DEFAULT_CONFIG_FILE_NAME,
  RepoKnowledgeConfigError,
  computeOutputSchemaDigest,
  computePromptDigest,
  computeTrustPolicyDigest,
  initializeStorage,
  loadRepoKnowledgeConfig,
  parseRepoKnowledgeConfig,
  resolveRepositoryPolicy,
  type ConfigErrorCode,
  type EffectiveRepositoryPolicy,
  type InitializedStorage,
} from "./config.js";
export {
  executeBufferedCommand,
  type BufferedCommandExecutor,
  type BufferedCommandRequest,
  type BufferedCommandResult,
} from "./buffered-command.js";
export {
  DEFAULT_GH_MAX_BUFFER_BYTES,
  DEFAULT_GH_TIMEOUT_MS,
  GhCommandError,
  GhRunner,
  type GhCommandErrorCode,
  type GhCommandErrorDetails,
  type GhCommandResult,
  type GhRunnerLike,
  type GhRunnerOptions,
} from "./gh-runner.js";
export {
  DEFAULT_REVIEW_COMMENT_PAGE_SIZE,
  DEFAULT_REVIEW_PAGE_SIZE,
  DEFAULT_REVIEW_THREAD_PAGE_SIZE,
  FETCH_PULL_REQUEST_REVIEWS_PAGE_QUERY,
  FETCH_PULL_REQUEST_SNAPSHOT_QUERY,
  FETCH_REVIEW_THREAD_COMMENTS_PAGE_QUERY,
  FETCH_REVIEW_THREADS_PAGE_QUERY,
  MAX_GRAPHQL_CONNECTION_PAGES,
  MAX_GRAPHQL_PAGE_SIZE,
  VALIDATE_PULL_REQUEST_SNAPSHOT_QUERY,
  GitHubPullRequestSnapshotClient,
  GitHubSnapshotError,
  reviewSummaryThreadId,
  type CompleteGitHubPullRequestSnapshot,
  type FetchGitHubPullRequestRequest,
  type GitHubPullRequestClientOptions,
  type GitHubPullRequestMetadata,
  type GitHubRepositoryMetadata,
  type GitHubReviewActor,
  type GitHubReviewComment,
  type GitHubReviewSummary,
  type GitHubReviewThread,
  type GitHubSnapshotErrorCode,
} from "./github-pull-request-client.js";
export {
  RAW_COMMENT_RECORD_TYPE,
  RAW_PULL_REQUEST_RECORD_TYPE,
  RAW_THREAD_RECORD_TYPE,
  GitHubSnapshotNormalizationError,
  buildReviewerIdentity,
  classifyCommentExclusion,
  computeDistillationInputDigest,
  computeThreadContentFingerprint,
  computeThreadDistillationKey,
  computeThreadStateFingerprint,
  isEmojiOnly,
  normalizeGitHubPullRequestSnapshot,
  normalizeLf,
  type CommentExclusionReason,
  type DistillationInputDigestRequest,
  type DistillationKeyRequest,
  type GitHubSnapshotNormalizationErrorCode,
  type GitHubSnapshotNormalizerOptions,
  type NormalizeGitHubPullRequestSnapshotRequest,
  type NormalizedDistillationActor,
  type NormalizedDistillationComment,
  type NormalizedDistillationThread,
  type NormalizedGitHubPullRequestSnapshot,
  type NormalizedRawObservationRecords,
  type RawOnlyReason,
  type ThreadDistillationDisposition,
  type UnknownBotWarning,
} from "./github-snapshot-normalizer.js";
export {
  PULL_REQUEST_SNAPSHOT_RECORD_TYPE,
  RAW_COMMENT_PATH,
  RAW_PULL_REQUEST_PATH,
  RAW_PULL_REQUEST_SNAPSHOT_PATH,
  RAW_THREAD_OBSERVATION_PATH,
  THREAD_REMOVED_RECORD_TYPE,
  GitHubIngestError,
  GitHubIngestService,
  type CompleteSnapshotFetcher,
  type GitHubIngestErrorCode,
  type GitHubIngestServiceOptions,
  type IngestPullRequestRequest,
  type IngestPullRequestResult,
  type IngestPullRequestSummary,
  type IngestRepositoryResolver,
} from "./github-ingest-service.js";
export {
  ExecaGitRemoteReader,
  GitRemoteError,
  parseGitHubRemoteUrl,
  type ExecaGitRemoteReaderOptions,
  type GitRemoteErrorCode,
  type GitRemoteReader,
} from "./git-remote.js";
export {
  ActorKindSchema,
  AiProviderSchema,
  CandidateIdSchema,
  CommentObservationSchema,
  DistillJobSchema,
  DistillJobStateSchema,
  DistillationOutputSchema,
  DistilledCandidateSchema,
  EventIdSchema,
  EvidenceActorSchema,
  EvidenceIdSchema,
  EvidenceStatusSchema,
  ExtractCandidateSchema,
  ExtractStableResponseSchema,
  ExtractSubmissionReceiptSchema,
  FinalizeStableResponseSchema,
  FinalizeSubmissionReceiptSchema,
  GitHubNodeIdSchema,
  HostAssistedDistillationConfigSchema,
  IngestConfigSchema,
  IsoDateTimeSchema,
  JobIdSchema,
  KnowledgeCategorySchema,
  KnowledgeEvidenceSchema,
  KnowledgeIdSchema,
  KnowledgeOutcomeSchema,
  KnowledgeRevisionPatchSchema,
  KnowledgeRevisionProposalSchema,
  KnowledgeRevisionProposalStatusSchema,
  KnowledgeStatusSchema,
  LlmConfigSchema,
  MergeDecisionRequiredStableResponseSchema,
  MergeDecisionSchema,
  MergeRelationSchema,
  NonEmptyStringSchema,
  ObservationIdSchema,
  PullRequestObservationSchema,
  PullRequestSnapshotSchema,
  RawObservationSchema,
  ReceiptIdSchema,
  RepoKnowledgeConfigSchema,
  RepositoryIdSchema,
  RepositoryNameSchema,
  RepositoryPolicySchema,
  ReviewerIdentitySchema,
  ScopePatternSchema,
  SeveritySchema,
  Sha256DigestSchema,
  SkipReasonSchema,
  SkippedStableResponseSchema,
  SnapshotIdSchema,
  SourceProviderSchema,
  SubmissionReceiptSchema,
  ThreadRemovedObservationSchema,
  ThreadObservationSchema,
  TransactionIdSchema,
  TrustConfigSchema,
  TrustLevelSchema,
  type CommentObservation,
  type DistillJob,
  type DistillationOutput,
  type DistilledCandidate,
  type EvidenceActor,
  type EvidenceStatus as DomainEvidenceStatus,
  type ExtractCandidate as DomainExtractCandidate,
  type ExtractStableResponse as DomainExtractStableResponse,
  type FinalizeStableResponse,
  type HostAssistedDistillationConfig,
  type IngestConfig,
  type KnowledgeCategory,
  type KnowledgeEvidence,
  type KnowledgeOutcome,
  type KnowledgeRevisionPatch,
  type KnowledgeRevisionProposal,
  type KnowledgeRevisionProposalStatus,
  type KnowledgeStatus,
  type LlmConfig,
  type MergeDecision,
  type MergeDecisionRequiredStableResponse as DomainMergeDecisionRequiredStableResponse,
  type PullRequestObservation,
  type PullRequestSnapshot,
  type RawObservation,
  type RepoKnowledgeConfig,
  type RepositoryPolicy,
  type ReviewerIdentity,
  type Severity,
  type SubmissionReceipt,
  type ThreadRemovedObservation,
  type ThreadObservation,
  type TrustConfig,
} from "./domain-schemas.js";
export {
  DOMAIN_ID_PREFIXES,
  createDomainId,
  type DomainIdKind,
} from "./ids.js";
export {
  DomainProjectionError,
  buildDomainProjectionSnapshot,
  projectKnowledgeDocuments,
  reduceDomainRecords,
  type DomainProjectionErrorCode,
  type DomainProjectionSnapshot,
  type ProjectedKnowledge,
  type ProjectedKnowledgeOutcome,
  type ReducedDomainProjection,
} from "./domain-projection.js";
export {
  DISTILLATION_JOB_AWAITING_FINALIZE,
  DISTILLATION_JOB_CREATED,
  DISTILLATION_JOB_FAILED,
  DISTILLATION_JOB_LEASED,
  DISTILLATION_JOB_LEASE_EXPIRED,
  DISTILLATION_JOB_LEASE_RENEWED,
  DISTILLATION_JOB_RECORD_TYPES,
  DISTILLATION_JOB_SKIPPED,
  DISTILLATION_JOB_SUCCEEDED,
  DistillationFailureKindSchema,
  DistillJobStateError,
  applyDistillationJobRecord,
  createDistillationJobEventRecord,
  jobUniqueKey,
  reduceDistillationJobRecords,
  type CreateDistillationJobEventRecordRequest,
  type DistillationFailureKind,
  type DistillationJobEvent,
  type DistillationJobEventPayload,
  type DistillationJobEventPayloadByType,
  type DistillationJobEventType,
  type DistillJobStateErrorCode,
} from "./distill-job-state.js";
export {
  DEFAULT_DISTILL_JOB_LEASE_DURATION_MS,
  DEFAULT_JSON_VALIDATION_RETRY_DELAY_MS,
  DISTILL_JOB_EVENT_PATH,
  DistillJobCoordinator,
  DistillJobCoordinatorError,
  assertCurrentDistillJobLease,
  hashLeaseToken,
  type AcquireDistillJobLeaseRequest,
  type CreateDistillJobRequest,
  type CreateDistillJobResult,
  type DistillJobCoordinatorErrorCode,
  type DistillJobCoordinatorOptions,
  type DistillJobLease,
  type DistillJobLeaseCredentials,
  type FailDistillJobRequest,
  type RenewDistillJobLeaseRequest,
  type SkipDistillJobRequest,
} from "./distill-job-coordinator.js";
export {
  ANTHROPIC_API_VERSION,
  ANTHROPIC_PROVIDER,
  DEFAULT_ANTHROPIC_MAX_TOKENS,
  DEFAULT_ANTHROPIC_MESSAGES_ENDPOINT,
  AnthropicProviderAdapter,
  type AnthropicProviderAdapterOptions,
} from "./anthropic-provider.js";
export {
  LlmProviderError,
  type LlmProviderAdapter,
  type LlmProviderErrorCode,
  type LlmProviderFailureKind,
  type StructuredCompletionRequest,
  type StructuredCompletionResponse,
} from "./llm-provider.js";
export {
  DISTILLATION_OUTPUT_JSON_SCHEMA,
  DISTILLATION_OUTPUT_SCHEMA_DIGEST,
  DISTILLATION_OUTPUT_SCHEMA_VERSION,
  buildDistillationUserInput,
  loadDistillationPrompt,
  parseDistillationPrompt,
  type BuildDistillationUserInputRequest,
  type DistillationPromptActor,
  type DistillationPromptComment,
  type DistillationPromptTemplate,
  type DistillationPromptThread,
} from "./distillation-prompt.js";
export {
  DEFAULT_PROVIDER_LEASE_HEARTBEAT_INTERVAL_MS,
  DistillationOutputValidationError,
  ProviderLeaseHeartbeatError,
  ProviderDistillationService,
  ProviderDistillationServiceError,
  evaluateProviderTransmission,
  parseDistillationOutput,
  startProviderLeaseHeartbeat,
  writeProviderDistillationDiagnostic,
  type DistillationProvenance,
  type ProviderDistillationDiagnostic,
  type ProviderDistillationDiagnosticEvent,
  type ProviderDistillationDiagnosticSink,
  type ProviderDistillationExtractedResult,
  type ProviderDistillationFailedResult,
  type ProviderDistillationPendingResult,
  type ProviderDistillationRunRequest,
  type ProviderDistillationRunResult,
  type ProviderDistillationServiceErrorCode,
  type ProviderDistillationServiceOptions,
  type ProviderDistillationThread,
  type ProviderLeaseHeartbeat,
  type ProviderTransmissionDecision,
  type ProviderTransmissionDeniedReason,
} from "./provider-distillation-service.js";
export {
  CanonicalJsonlError,
  canonicalJsonlLineSha256,
  parseCanonicalJsonlLine,
  serializeCanonicalJsonlRecord,
  type CanonicalJsonlRecord,
} from "./canonical-jsonl.js";
export {
  CanonicalStoreError,
  CanonicalTransactionStore,
  KnowledgeConflictError,
  type CanonicalAppendRecordRequest,
  type CanonicalCommitPoint,
  type CanonicalFaultContext,
  type CanonicalFaultInjector,
  type CanonicalFileWriteRequest,
  type CanonicalLockedMutation,
  type CanonicalLockedMutationPlanner,
  type CanonicalLockedSearchMutationPlanner,
  type CanonicalStoreErrorCode,
  type CanonicalTransactionRequest,
  type CanonicalTransactionStoreOptions,
  type KnowledgeUpdateRequest,
} from "./canonical-transaction-store.js";
export {
  EVIDENCE_EVENT_PATH,
  REVISION_PROPOSAL_EVENT_PATH,
  CanonicalFinalizeError,
  CanonicalFinalizeService,
  type CanonicalFinalizeErrorCode,
  type CanonicalFinalizeRequest,
  type CanonicalFinalizeServiceOptions,
  type CanonicalFinalizeSourceBinding,
  type CanonicalSkipFinalizeRequest,
  type CanonicalSkipFinalizeResult,
} from "./canonical-finalize-service.js";
export {
  DEFINITIVE_NON_KNOWLEDGE_SKIP_REASONS,
  applySkipReasonPolicy,
  isDefinitiveNonKnowledge,
  type DefinitiveNonKnowledgeSkipReason,
  type EvidenceRecord,
  type EvidenceStatus,
  type ManualReviewMarker,
  type SkipPolicyInput,
  type SkipPolicyResult,
  type SkipReason,
  type SkippedStableResponse,
} from "./evidence-policy.js";
export {
  FinalizeGuard,
  FinalizeGuardError,
  computeContentFingerprint,
  computeDistillationKey,
  computeMatchSetDigest,
  normalizePossibleMatchBindings,
  type CurrentFinalizeSource,
  type DistillationKeyInput,
  type FinalizeContext,
  type FinalizeGuardDependencies,
  type FinalizeGuardErrorCode,
  type FinalizeJob,
  type FingerprintComment,
} from "./finalize-guard.js";
export {
  normalizePossibleMatchSets,
  type PossibleKnowledgeMatch,
  type PossibleKnowledgeMatchBinding,
  type PossibleMatchBinding,
  type PossibleMatchSet,
  type PossibleMatchStatus,
} from "./possible-match.js";
export {
  DEFAULT_MERGE_CANDIDATE_LIMIT,
  MAX_MERGE_CANDIDATE_LIMIT,
  MIN_MERGE_CANDIDATE_LIMIT,
  MergeCandidateSearchError,
  MergeCandidateSearchService,
  collapseExactCandidateRules,
  createMergeCandidateSearchPlan,
  normalizeCandidateRule,
  resolveMergeCandidateSearch,
  scopesMayOverlap,
  type CreateMergeCandidateSearchPlanRequest,
  type MergeCandidateSearchErrorCode,
  type MergeCandidateSearchPlan,
  type MergeCandidateSearchRepository,
  type MergeCandidateSearchRequest,
  type MergeCandidateSearchResult,
  type MergeCandidateSearchServiceOptions,
  type SearchableCandidate,
} from "./merge-candidate-service.js";
export {
  ProviderDistillationPipeline,
  type ProviderDistillationPipelineFinalizedResult,
  type ProviderDistillationPipelineOptions,
  type ProviderDistillationPipelineResult,
  type ProviderDistillationPipelineSkippedResult,
} from "./provider-distillation-pipeline.js";
export {
  MERGE_CLASSIFIER_OUTPUT_JSON_SCHEMA,
  MERGE_CLASSIFIER_OUTPUT_SCHEMA_VERSION,
  MERGE_CLASSIFIER_SYSTEM_PROMPT,
  MergeClassifierError,
  ProviderMergeRelationClassifier,
  buildMergeClassifierInput,
  parseProviderMergeDecisions,
  validateMergeDecisions,
  type MergeClassificationRequest,
  type MergeClassificationResult,
  type MergeClassifierErrorCode,
  type MergeRelationClassifier,
  type ProviderMergeRelationClassifierOptions,
} from "./merge-classifier.js";
export {
  ProjectionStaleError,
  buildKnowledgeProjection,
  computeKnowledgeFileState,
  ensureProjectionCurrent,
  isProjectionCurrent,
  readKnowledgeSnapshot,
  type KnowledgeFile,
  type KnowledgeFileHash,
  type KnowledgeFileState,
  type KnowledgeProjection,
  type KnowledgeProjectionBuilder,
  type KnowledgeSnapshot,
} from "./knowledge-file-state.js";
export {
  KnowledgeStoreInvalidError,
  applyKnowledgeDocumentPatch,
  computeByteSha256,
  parseKnowledgeDocument,
  serializeKnowledgeDocument,
  type KnowledgeDocument,
  type KnowledgeDocumentPatch,
  type KnowledgeFrontmatter,
} from "./knowledge-document.js";
export {
  DEFAULT_KNOWLEDGE_SEARCH_CANDIDATE_LIMIT,
  MAX_KNOWLEDGE_SEARCH_CANDIDATE_LIMIT,
  MAX_KNOWLEDGE_SEARCH_QUERY_CODE_POINTS,
  KnowledgeSearchError,
  computeKnowledgeSearchScore,
  escapeLikeLiteral,
  evidenceBoost,
  normalizeKnowledgeSearchQuery,
  reciprocalRank,
  severityBoost,
  toFtsLiteral,
  validateKnowledgeSearchCandidateLimit,
  violationBoost,
  type KnowledgeSearchErrorCode,
  type ExhaustiveKnowledgeSearchRequest,
  type KnowledgeSearchHit,
  type KnowledgeSearchMode,
  type KnowledgeSearchRequest,
  type KnowledgeSearchResult,
  type NormalizedKnowledgeSearchQuery,
} from "./knowledge-search.js";
export {
  DEFAULT_EVIDENCE_LIMIT,
  DEFAULT_GET_RULES_LIMIT,
  DEFAULT_SEARCH_KNOWLEDGE_LIMIT,
  MAX_EVIDENCE_LIMIT,
  MAX_READ_RESULT_LIMIT,
  KnowledgeReadError,
  KnowledgeReadService,
  encodeEvidenceCursor,
  normalizeRepositoryFilePath,
  type GetKnowledgeRequest,
  type GetKnowledgeResult,
  type GetRulesRequest,
  type GetRulesResult,
  type GetRulesRule,
  type KnowledgeDetail,
  type KnowledgeReadErrorCode,
  type KnowledgeReadRepository,
  type KnowledgeReadServiceOptions,
  type RuleMatchReason,
  type SearchKnowledgeItem,
  type SearchKnowledgeRequest,
  type SearchKnowledgeResult,
} from "./knowledge-read-service.js";
export { FileLockTimeoutError, withPosixFileLock } from "./posix-file-lock.js";
export {
  RequestIntegrityError,
  SubmissionIdempotencyStore,
  buildRequestHashPayload,
  computeRequestSha256,
  issueRequestBoundToken,
  verifyRequestBoundToken,
  type AcceptedSubmissionRegistration,
  type ExpectedRequestBoundToken,
  type ExtractRequest,
  type ExtractRequestHashPayload,
  type FinalizeRequest,
  type FinalizeRequestHashPayload,
  type IssueRequestBoundTokenInput,
  type PhaseRequest,
  type ReplaySubmissionRegistration,
  type RequestBoundTokenClaims,
  type RequestBoundTokenKind,
  type RequestHashPayload,
  type RequestIntegrityErrorCode,
  type SubmissionRegistration,
} from "./request-integrity.js";
export {
  InMemoryReceiptStore,
  ReceiptReplayEngine,
  ReceiptReplayError,
  type ExtractCandidate,
  type ExtractReceipt,
  type ExtractReplayResult,
  type ExtractRuntimeResponse,
  type ExtractStableResponse,
  type FinalizeReceipt,
  type FinalizeReplayResult,
  type MergeDecisionRequiredRuntimeResponse,
  type MergeDecisionRequiredStableResponse,
  type Receipt,
  type ReceiptMissResult,
  type ReceiptReplayDependencies,
  type ReceiptReplayErrorCode,
  type ReceiptReplayResult,
  type ReceiptStore,
  type ReplayJob,
} from "./receipt-replay.js";
export {
  RepositoryRegistry,
  RepositoryRegistryError,
  repositoryStorageId,
  type RegisterRepositoryRequest,
  type RepositoryRegistryEntry,
  type RepositoryRegistryErrorCode,
  type RepositoryRegistryOptions,
  type ResolvedRepository,
} from "./repository-registry.js";
export {
  RESOLVE_REPOSITORY_GRAPHQL,
  RepositoryResolutionError,
  RepositoryResolver,
  parseRepositoryName,
  resolveAllowedWorkspacePath,
  type RepositoryRegistryWriter,
  type RepositoryResolution,
  type RepositoryResolutionErrorCode,
  type RepositoryResolutionErrorDetails,
  type RepositoryResolutionInput,
  type RepositoryResolutionSource,
  type RepositoryResolverOptions,
} from "./repository-resolver.js";
export {
  SqliteCanonicalProjection,
  type CanonicalKnowledgeReadView,
  type CanonicalKnowledgeSearchView,
  type CanonicalProjectionSnapshot,
  type ProjectedCanonicalRecord,
} from "./sqlite-projection.js";
